name: scrape
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' #run this code every five minitus
    #cron expression:https://docs.oracle.com/cd/E12058_01/doc/doc.1014/e12030/cron_expressions.htm
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install all necessary packages
        run: pip install requests beautifulsoup4 pandas
      - name: Run the scraping script
        run: python scraper.py
      - name: Commit and push if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push